# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MJRefreshExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LookinServer', :configurations => ['Debug']

  # Pods for MJRefreshExample

  target 'MJRefreshExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MJRefreshFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MJRefreshFramework

end
