# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestVC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestVC
  pod 'MMKV'

  pod 'SDWebImage'#,'~>3.8.2'
  pod 'SDWebImage/WebP'
  pod 'SDWebImage/GIF'
  
#  pod 'SDWebImageYYPlugin'
  
  pod 'YYWebImage'
  
  pod 'Shimmer'
  pod 'YYDispatchQueuePool' # 队列池
  pod 'LookinServer', :configurations => ['Debug']
  
  target 'TestVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestVCUITests' do
    # Pods for testing
  end

end
