name: build
on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
jobs: 
  build:
    runs-on: macos-11.0
    strategy:
      max-parallel: 2
      matrix:  
        configuration: [debug, release]
        scheme: [objc, objc-inspect]
        arch: [x86_64] 
        sdk: [macosx]
    steps:
    - uses: actions/checkout@v2
    - run: |
        xcodebuild -workspace objc.xcworkspace \
          -scheme ${{ matrix.scheme }} \
          -configuration ${{ matrix.configuration }} \
          -arch ${{ matrix.arch }} \
          -sdk ${{ matrix.sdk }}
